### ISSUE TITLE
Hugo doesn't render the MD '-[ ]' like GitHub

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#55]
Compare:
- [https://docs.nlx.io/functional/product-vision/](https://docs.nlx.io/functional/product-vision/)
- [https://github.com/VNG-Realisatie/nlx/blob/master/docs/content/functional/product-vision.md](https://github.com/VNG-Realisatie/nlx/blob/master/docs/content/functional/product-vision.md)

Checkboxes are not rendered, what is recommended way to fix?

**Comment by ehotting** [comment]
Related: https://gohugo.io/content-management/formats/#extend-markdown

**Comment by GeertJohan** [comment]
Just fixed it in a direct commit. f2107602b8bca56ff670abbad999affd4939c57e
Restarted the docs container as well, please see https://docs.nlx.io/functional/product-vision/
The problem was the missing empty line before the list starts. Apparently Hugo is stricter about the Markdown syntax than GitHub is. Hugo does by default support the extended markdown features as linked by @ehotting .

Closing this as I think there's nothing we need to change in the hugo setup as this was a syntax error. Please feel free to re-open if you believe changes are still required.
