### ISSUE TITLE
As product owner I want NLX to be compliant with relevant law and regulations

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/nlx#9]
- [ ] Analyse impact of [eIDAS regulation](http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32014R0910&from=EN)
- [x] Analyse impact of [The New European Interoperability Framework](https://ec.europa.eu/isa2/eif_en)
- [ ] [ICT Beveiligingsrichtlijnen voor Webapplicaties](https://www.ncsc.nl/actueel/whitepapers/ict-beveiligingsrichtlijnen-voor-webapplicaties.html), NCSC
- [ ] ...
- [ ] Define extra user stories based on analysis

**Comment by arnoudquanjer** [comment]
I've added an Excel file which details the relevant requirements for NLX from the European Interoperability Framework. 

[EIF recommendations in relation to NLX.xlsx](https://github.com/VNG-Realisatie/nlx/files/1672485/EIF.recommendations.in.relation.to.NLX.xlsx)

**Comment by ehotting** [comment]
Thanks! On first sight, only number 16 comes some work. In my opinion, NLX aims at developers so we can (should) use English only - we can formulate the rationale. We do have to make perfectly clear where multilingual support is added. RSGB and RGBZ are Dutch. What about the names of methods? Something to discuss.

**Comment by arnoudquanjer** [comment]
I agree, number 16 is the only requirement that either requires some work. All the other requirements are implemented by NLX.

I also think reformulate the rationale to indicate where multilingual support is implemented. The main language in my opinion should be English as we mainly target developers. That applies to documentation, method names etc. Where multilingual support might be beneficial is in the API descriptions and the user interface of the API discovery tooling. As you already said the information models defined by VNG-R are also a discussion point. All those models are in Dutch. Something we need to discuss in the StUF-regiegroep?

**Comment by bvhme** [comment]
I feel this is a good point to bring up a key decision. Are we making a thing that can only be used by VNG-Realisatie and it's partners, or are we building a more general piece of software and an implementation for VNG-Realisatie?

I find the former to be suboptimal since it would negate most of the benefits of Open Source and leaves us vulnerable to building a system that doesn't scale and thus needs to be replaced by a new standard relatively quickly.

The latter means we need to be a universal and extensible core that can be adapted to also work for the VNG-Realisatie case whilst also being able to be implemented in other contexts. With broader adoption, the benefits of Open Source can really be realised.

The latter would mean that the specific Dutch-law related things are best kept in projects that extend NLX.

I'm also eager to draw clear lines between NLX the software product and NLX the platform.

**Comment by ehotting** [comment]
This more general piece of software doesn't need a specific implementation to function within relevant law. Being generic and compliant with more local regulations are not mutually exclusive. Most law has no limiting impact on NLX, and where regulations apply, those only benefit the project. For example, the European Interoperability Framework comes with lots of recommendations that were all already met, yet recommendation 16 advices "multilingualism". That will require some discussion (where is the line between software and content when it comes to API's and considered local law), but if we implement it correctly, the software becomes more universally useable.
